# Generated by Django 3.0.3 on 2020-07-12 07:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200711_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='events', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(blank=True, default='blog_images/image_1.jpg', null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 7, 55, 0, 672790, tzinfo=utc)),
        ),
    ]
